# example https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
[project]
name = "torch_practice"
version = "0.0.1"
description = "Practice Pytorch, Ray, and packaging."
authors = [{ name = " Santiago Miranda", email = "santimir.me@gmail.com" }]
readme = "README.md"
license = { text = "MIT License" }
requires-python = ">=3.10"
keywords = ["sample project", "pytorch", "ray"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: Unix",
]


dependencies = [
    "matplotlib>=3.9.2",
    "ray[train,tune]>=2.39.0",
    "torchinfo>=1.8.0",
]


[project.urls]
Homepage = "https://github.com/ghsanti/learn_python"
Repository = "https://github.com/ghsanti/learn_python"
Issues = "https://github.com/ghsanti/learn_python/issues"
Documentation = "https://readthedocs.org"
Changelog = "https://github.com/ghsanti/learn_python/blob/main/CHANGELOG.md"

[build-system]
# other builds backends are setuptools etc 
# normally setuptools uses setup.cfg, setup.py etc.
# the build frontend (pip etc.) calls the backend.
# and they make the wheels / `.whl` files.
# those files are the ones distributed.
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/torch_practice"]
